# Generated by Django 5.2.3 on 2025-07-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdt', '0002_normafdt_delete_resultadofdt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormaFDT',
        ),
    ]
