# Generated by Django 5.2.4 on 2025-07-02 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdt', '0004_initial'),
        ('pacientes', '0002_paciente_email_paciente_endereco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoFDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(auto_now_add=True)),
                ('fase', models.CharField(choices=[('Leitura', 'Leitura'), ('Contagem', 'Contagem'), ('Escolha', 'Escolha'), ('Alternância', 'Alternância'), ('Inibição', 'Inibição'), ('Flexibilidade', 'Flexibilidade')], max_length=20)),
                ('tempo_segundos', models.FloatField(blank=True, null=True)),
                ('erros', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado FDT',
                'verbose_name_plural': 'Resultados FDT',
                'ordering': ['-data_aplicacao'],
            },
        ),
    ]
